package com.andreas.personalcloudclient;

import android.content.Context;

import okhttp3.OkHttpClient;
import okhttp3.logging.HttpLoggingInterceptor;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public class RetrofitClient {
    private static Retrofit retrofit = null;

    /**
     * Gets the singleton instance of the main Retrofit client.
     * This client is configured with interceptors for logging and automatic authentication.
     * It also includes an authenticator for automatic token refreshing.
     *
     * @param context The application context.
     * @return The configured Retrofit instance.
     */
    public static Retrofit getClient(Context context) {
        if (retrofit == null) {
            // The base URL is fetched from the string resources that were
            // auto-generated by Gradle. This keeps the URL out of the source code.
            final String BASE_URL = context.getApplicationContext().getString(R.string.api_base_url);

            // 1. Set up the logging interceptor for debugging network requests.
            HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor();
            loggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);

            // 2. Set up custom interceptor to add the auth token to headers.
            AuthInterceptor authInterceptor = new AuthInterceptor(context);

            // 3. Set up custom authenticator to handle 401 errors and refresh the token.
            TokenAuthenticator tokenAuthenticator = new TokenAuthenticator(context);

            // 4. Build the OkHttpClient, adding all components.
            OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(authInterceptor)      // Runs first to add the token.
                .addInterceptor(loggingInterceptor)  // Runs second to log the request with the token.
                .authenticator(tokenAuthenticator)   // Runs ONLY if the server returns a 401 error.
                .build();

            // 5. Build the Retrofit instance using custom client.
            retrofit = new Retrofit.Builder()
                .baseUrl(BASE_URL)
                .client(client)
                .addConverterFactory(GsonConverterFactory.create())
                .build();
        }
        return retrofit;
    }

    /**
     * Gets a specialized ApiService for downloading files with progress listening.
     *
     * @param listener The listener to report download progress.
     * @return A specialized ApiService instance.
     */
    public static ApiService getDownloadApiService(Context context, DownloadProgressListener listener) {
        // The base URL must also be fetched here for this specialized client.
        final String BASE_URL = context.getApplicationContext().getString(R.string.api_base_url);

        // --- ADD THE AUTHENTICATION COMPONENTS ---
        AuthInterceptor authInterceptor = new AuthInterceptor(context);
        TokenAuthenticator tokenAuthenticator = new TokenAuthenticator(context);

        // Build an OkHttpClient that has ALL THREE components.
        OkHttpClient downloadClient = new OkHttpClient.Builder()
            .addInterceptor(authInterceptor)         // Adds the auth token
            .addInterceptor(new DownloadProgressInterceptor(listener)) // Reports progress
            .authenticator(tokenAuthenticator)      // Refreshes the token if needed
            .build();

        Retrofit downloadRetrofit = new Retrofit.Builder()
            .baseUrl(BASE_URL)
            .client(downloadClient)
            .build();

        return downloadRetrofit.create(ApiService.class);
    }
}
